### ISSUE TITLE
Inappropriate return statement in auction demo example

### ISSUE THREAD

**Issue by piachristel** [hyperledger-labs/fabric-secure-chaincode#23]
In my opinion, some return statements in the fabric-secure-chaincode/ecc_enclave/enclave/auction/auction_cc.cpp  are not correct. For example in the following section of the `auction_submit` method (line 115-118):
```
 if (auction_bytes_len == 0) {
        LOG_DEBUG("AuctionCC: Auction does not exist");
        return AUCTION_ALREADY_EXISTS; 
}
```
Shouldn't it return a AUCTION_DOES_NOT_EXIST? Which would imply the definition of an appropriate #define alias.

**Comment by mbrandenburger** [comment]
Yes, you are right. Would you like to submit a CR for fixing this?

**Comment by piachristel** [comment]
Yes, I will :)
